### ISSUE TITLE
Proposal: simplify null coalescing operator

### ISSUE THREAD

**Issue by nxuv** [xiangnanscu/js2lua#9]
Right now `a = a ?? b` generates:
```lua
a = (function()
    if a == nil then
        return b
    else
        return a
    end
end)()
```
Where it would be sufficient to generate simple `a = a or b`

**Comment by xiangnanscu** [comment]
when `a` is false, `a ?? b`  should resolve to `a`, but `a or b` will resolve to `b`

**Comment by nxuv** [comment]
Oh, my bad then in that, but still generated code could be cleaner

**Comment by nxuv** [comment]
> The nullish coalescing (??) operator is a logical operator that returns its right-hand side operand when its left-hand side operand is null or undefined, and otherwise returns its left-hand side operand.

I take my words back, it resolves the same as `a or b`

**Comment by xiangnanscu** [comment]
You can test it by typing `false ?? 1` and `false || 1` in the console.

**Comment by nxuv** [comment]
Oh, you're talking about that. Well, this is kind of complicated then since in Lua prople usually ignore boolean type and concentrate on nil'ish part which is equal to false.

But I do understand your point
